language: elixir

elixir:
  - 1.6.6

services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/test.exs.travis config/test.exs

addons:
  postgresql: "9.4"
